[2023-10-25T12:00:11.662+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_dag.submit_spark_word_count_job manual__2023-10-25T06:24:33.942586+00:00 [queued]>
[2023-10-25T12:00:11.667+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_dag.submit_spark_word_count_job manual__2023-10-25T06:24:33.942586+00:00 [queued]>
[2023-10-25T12:00:11.667+0530] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-10-25T12:00:11.676+0530] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): submit_spark_word_count_job> on 2023-10-25 06:24:33.942586+00:00
[2023-10-25T12:00:11.679+0530] {standard_task_runner.py:57} INFO - Started process 52789 to run task
[2023-10-25T12:00:11.681+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'wikipedia_dag', 'submit_spark_word_count_job', 'manual__2023-10-25T06:24:33.942586+00:00', '--job-id', '1274', '--raw', '--subdir', 'DAGS_FOLDER/word_count.py', '--cfg-path', '/tmp/tmp8yu7mque']
[2023-10-25T12:00:11.682+0530] {standard_task_runner.py:85} INFO - Job 1274: Subtask submit_spark_word_count_job
[2023-10-25T12:00:11.704+0530] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_dag.submit_spark_word_count_job manual__2023-10-25T06:24:33.942586+00:00 [running]> on host harika-Latitude-5511
[2023-10-25T12:00:11.746+0530] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='harikasree2225@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='wikipedia_dag' AIRFLOW_CTX_TASK_ID='submit_spark_word_count_job' AIRFLOW_CTX_EXECUTION_DATE='2023-10-25T06:24:33.942586+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-25T06:24:33.942586+00:00'
[2023-10-25T12:00:11.750+0530] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2023-10-25T12:00:11.750+0530] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master yarn --name PythonWordCount --queue root.default /home/harika/sparkjobs/word_count_extended.py /home/harika/wikidata/Vegetable/content.txt
[2023-10-25T12:00:12.789+0530] {spark_submit.py:491} INFO - 23/10/25 12:00:12 WARN Utils: Your hostname, harika-Latitude-5511 resolves to a loopback address: 127.0.1.1; using 192.168.29.76 instead (on interface wlo1)
[2023-10-25T12:00:12.791+0530] {spark_submit.py:491} INFO - 23/10/25 12:00:12 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2023-10-25T12:00:12.858+0530] {spark_submit.py:491} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2023-10-25T12:00:12.859+0530] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2023-10-25T12:00:12.859+0530] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2023-10-25T12:00:12.859+0530] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2023-10-25T12:00:12.859+0530] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2023-10-25T12:00:12.859+0530] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2023-10-25T12:00:12.859+0530] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2023-10-25T12:00:12.859+0530] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2023-10-25T12:00:12.859+0530] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2023-10-25T12:00:12.859+0530] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2023-10-25T12:00:12.859+0530] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-10-25T12:00:12.895+0530] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name PythonWordCount --queue root.default /home/harika/sparkjobs/word_count_extended.py /home/harika/wikidata/Vegetable/content.txt. Error code is: 1.
[2023-10-25T12:00:12.900+0530] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=wikipedia_dag, task_id=submit_spark_word_count_job, execution_date=20231025T062433, start_date=20231025T063011, end_date=20231025T063012
[2023-10-25T12:00:12.926+0530] {logging_mixin.py:151} WARNING - /home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-10-25T12:00:12.926+0530] {configuration.py:1063} WARNING - section/key [smtp/smtp_user] not found in config
[2023-10-25T12:00:12.927+0530] {email.py:270} INFO - Email alerting: attempt 1
[2023-10-25T12:00:12.930+0530] {configuration.py:1063} WARNING - section/key [smtp/smtp_user] not found in config
[2023-10-25T12:00:12.930+0530] {email.py:270} INFO - Email alerting: attempt 1
[2023-10-25T12:00:12.930+0530] {taskinstance.py:2005} ERROR - Failed to send email to: ['harikasree2225@gmail.com']
Traceback (most recent call last):
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name PythonWordCount --queue root.default /home/harika/sparkjobs/word_count_extended.py /home/harika/wikidata/Vegetable/content.txt. Error code is: 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2418, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2003, in handle_failure
    self.email_alert(error, task)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2023-10-25T12:00:12.938+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 1274 for task submit_spark_word_count_job (Cannot execute: spark-submit --master yarn --name PythonWordCount --queue root.default /home/harika/sparkjobs/word_count_extended.py /home/harika/wikidata/Vegetable/content.txt. Error code is: 1.; 52789)
[2023-10-25T12:00:12.976+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-25T12:00:12.989+0530] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
