[2023-10-18T13:52:31.032+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_dag.get_details_from_wikipedia_task scheduled__2023-10-16T00:00:00+00:00 [queued]>
[2023-10-18T13:52:31.036+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_dag.get_details_from_wikipedia_task scheduled__2023-10-16T00:00:00+00:00 [queued]>
[2023-10-18T13:52:31.036+0530] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-10-18T13:52:31.046+0530] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): get_details_from_wikipedia_task> on 2023-10-16 00:00:00+00:00
[2023-10-18T13:52:31.048+0530] {standard_task_runner.py:57} INFO - Started process 65702 to run task
[2023-10-18T13:52:31.050+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'wikipedia_dag', 'get_details_from_wikipedia_task', 'scheduled__2023-10-16T00:00:00+00:00', '--job-id', '334', '--raw', '--subdir', 'DAGS_FOLDER/word_count.py', '--cfg-path', '/tmp/tmp59y15aa_']
[2023-10-18T13:52:31.050+0530] {standard_task_runner.py:85} INFO - Job 334: Subtask get_details_from_wikipedia_task
[2023-10-18T13:52:31.074+0530] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_dag.get_details_from_wikipedia_task scheduled__2023-10-16T00:00:00+00:00 [running]> on host harika-Latitude-5511
[2023-10-18T13:52:31.110+0530] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='harikasree2k@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='wikipedia_dag' AIRFLOW_CTX_TASK_ID='get_details_from_wikipedia_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-16T00:00:00+00:00'
[2023-10-18T13:52:31.110+0530] {logging_mixin.py:151} INFO - Artificial intelligence
[2023-10-18T13:52:33.199+0530] {logging_mixin.py:151} INFO - Artificial intelligence
[2023-10-18T13:52:34.933+0530] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/harika/airflow/dags/word_count.py", line 46, in get_details_from_wikipedia_api
    os.makedirs(download_folder)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/wikidata'
[2023-10-18T13:52:34.943+0530] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=wikipedia_dag, task_id=get_details_from_wikipedia_task, execution_date=20231016T000000, start_date=20231018T082231, end_date=20231018T082234
[2023-10-18T13:52:34.967+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 334 for task get_details_from_wikipedia_task ([Errno 13] Permission denied: '/home/wikidata'; 65702)
[2023-10-18T13:52:34.998+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-18T13:52:35.037+0530] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
