[2023-10-30T18:04:40.487+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xcomEx2.training_model_C manual__2023-10-30T12:34:29.947867+00:00 [queued]>
[2023-10-30T18:04:40.493+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xcomEx2.training_model_C manual__2023-10-30T12:34:29.947867+00:00 [queued]>
[2023-10-30T18:04:40.494+0530] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-30T18:04:40.502+0530] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): training_model_C> on 2023-10-30 12:34:29.947867+00:00
[2023-10-30T18:04:40.507+0530] {standard_task_runner.py:57} INFO - Started process 531052 to run task
[2023-10-30T18:04:40.509+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'xcomEx2', 'training_model_C', 'manual__2023-10-30T12:34:29.947867+00:00', '--job-id', '1975', '--raw', '--subdir', 'DAGS_FOLDER/xcom2.py', '--cfg-path', '/tmp/tmp1tqkjf2s']
[2023-10-30T18:04:40.509+0530] {standard_task_runner.py:85} INFO - Job 1975: Subtask training_model_C
[2023-10-30T18:04:40.532+0530] {task_command.py:415} INFO - Running <TaskInstance: xcomEx2.training_model_C manual__2023-10-30T12:34:29.947867+00:00 [running]> on host harika-Latitude-5511
[2023-10-30T18:04:40.577+0530] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='xcomEx2' AIRFLOW_CTX_TASK_ID='training_model_C' AIRFLOW_CTX_EXECUTION_DATE='2023-10-30T12:34:29.947867+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-30T12:34:29.947867+00:00'
[2023-10-30T18:04:40.578+0530] {logging_mixin.py:151} INFO - model's accuracy: 5.7929589994536865
[2023-10-30T18:04:40.578+0530] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/harika/airflow/dags/xcom2.py", line 15, in _training_model
    ti.xcom_push(key=modal_accuracy, value=accuracy)
NameError: name 'modal_accuracy' is not defined
[2023-10-30T18:04:40.580+0530] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=xcomEx2, task_id=training_model_C, execution_date=20231030T123429, start_date=20231030T123440, end_date=20231030T123440
[2023-10-30T18:04:40.586+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 1975 for task training_model_C (name 'modal_accuracy' is not defined; 531052)
[2023-10-30T18:04:40.600+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-30T18:04:40.610+0530] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
