[2023-10-23T12:58:07.550+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: webpage_dag.get_details_from_url_task manual__2023-10-23T07:19:34.247157+00:00 [queued]>
[2023-10-23T12:58:07.555+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: webpage_dag.get_details_from_url_task manual__2023-10-23T07:19:34.247157+00:00 [queued]>
[2023-10-23T12:58:07.555+0530] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-10-23T12:58:07.563+0530] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): get_details_from_url_task> on 2023-10-23 07:19:34.247157+00:00
[2023-10-23T12:58:07.566+0530] {standard_task_runner.py:57} INFO - Started process 13772 to run task
[2023-10-23T12:58:07.568+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'webpage_dag', 'get_details_from_url_task', 'manual__2023-10-23T07:19:34.247157+00:00', '--job-id', '794', '--raw', '--subdir', 'DAGS_FOLDER/word_count_url.py', '--cfg-path', '/tmp/tmppiq6jn7t']
[2023-10-23T12:58:07.569+0530] {standard_task_runner.py:85} INFO - Job 794: Subtask get_details_from_url_task
[2023-10-23T12:58:07.589+0530] {task_command.py:415} INFO - Running <TaskInstance: webpage_dag.get_details_from_url_task manual__2023-10-23T07:19:34.247157+00:00 [running]> on host harika-Latitude-5511
[2023-10-23T12:58:07.629+0530] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='harikasree2225@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='webpage_dag' AIRFLOW_CTX_TASK_ID='get_details_from_url_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-23T07:19:34.247157+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-23T07:19:34.247157+00:00'
[2023-10-23T12:58:09.677+0530] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/harika/airflow/dags/word_count_url.py", line 40, in get_details_from_url
    download_folder = os.path.join(DOWNLOAD_LOCATION, 'web_page_data')
NameError: name 'DOWNLOAD_LOCATION' is not defined
[2023-10-23T12:58:09.679+0530] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=webpage_dag, task_id=get_details_from_url_task, execution_date=20231023T071934, start_date=20231023T072807, end_date=20231023T072809
[2023-10-23T12:58:09.693+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 794 for task get_details_from_url_task (name 'DOWNLOAD_LOCATION' is not defined; 13772)
[2023-10-23T12:58:09.708+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-23T12:58:09.722+0530] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
