[2023-10-18T16:06:03.057+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_emailOperator.send_email scheduled__2023-10-18T10:35:00+00:00 [queued]>
[2023-10-18T16:06:03.061+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_emailOperator.send_email scheduled__2023-10-18T10:35:00+00:00 [queued]>
[2023-10-18T16:06:03.061+0530] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-18T16:06:03.069+0530] {taskinstance.py:1380} INFO - Executing <Task(EmailOperator): send_email> on 2023-10-18 10:35:00+00:00
[2023-10-18T16:06:03.071+0530] {standard_task_runner.py:57} INFO - Started process 77941 to run task
[2023-10-18T16:06:03.073+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'hello_emailOperator', 'send_email', 'scheduled__2023-10-18T10:35:00+00:00', '--job-id', '376', '--raw', '--subdir', 'DAGS_FOLDER/hello_emailOperator.py', '--cfg-path', '/tmp/tmp2e7e3wu4']
[2023-10-18T16:06:03.073+0530] {standard_task_runner.py:85} INFO - Job 376: Subtask send_email
[2023-10-18T16:06:03.096+0530] {task_command.py:415} INFO - Running <TaskInstance: hello_emailOperator.send_email scheduled__2023-10-18T10:35:00+00:00 [running]> on host harika-Latitude-5511
[2023-10-18T16:06:03.131+0530] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='peter' AIRFLOW_CTX_DAG_ID='hello_emailOperator' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2023-10-18T10:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-18T10:35:00+00:00'
[2023-10-18T16:06:03.139+0530] {logging_mixin.py:151} WARNING - /home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-10-18T16:06:03.139+0530] {configuration.py:1063} WARNING - section/key [smtp/smtp_user] not found in config
[2023-10-18T16:06:03.139+0530] {email.py:270} INFO - Email alerting: attempt 1
[2023-10-18T16:06:03.139+0530] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/operators/email.py", line 77, in execute
    send_email(
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2023-10-18T16:06:03.142+0530] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=hello_emailOperator, task_id=send_email, execution_date=20231018T103500, start_date=20231018T103603, end_date=20231018T103603
[2023-10-18T16:06:03.148+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 376 for task send_email ([Errno 111] Connection refused; 77941)
[2023-10-18T16:06:03.165+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-18T16:06:03.176+0530] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
