[2023-10-17T15:45:25.970+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pdf_extract.extract_text_from_pdf manual__2023-10-17T10:15:23.376443+00:00 [queued]>
[2023-10-17T15:45:25.979+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pdf_extract.extract_text_from_pdf manual__2023-10-17T10:15:23.376443+00:00 [queued]>
[2023-10-17T15:45:25.979+0530] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-17T15:45:25.993+0530] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_text_from_pdf> on 2023-10-17 10:15:23.376443+00:00
[2023-10-17T15:45:25.996+0530] {standard_task_runner.py:57} INFO - Started process 39612 to run task
[2023-10-17T15:45:25.998+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'pdf_extract', 'extract_text_from_pdf', 'manual__2023-10-17T10:15:23.376443+00:00', '--job-id', '318', '--raw', '--subdir', 'DAGS_FOLDER/pdf_extract.py', '--cfg-path', '/tmp/tmp4ynvedv1']
[2023-10-17T15:45:25.999+0530] {standard_task_runner.py:85} INFO - Job 318: Subtask extract_text_from_pdf
[2023-10-17T15:45:26.034+0530] {task_command.py:415} INFO - Running <TaskInstance: pdf_extract.extract_text_from_pdf manual__2023-10-17T10:15:23.376443+00:00 [running]> on host harika-Latitude-5511
[2023-10-17T15:45:26.098+0530] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pdf_extract' AIRFLOW_CTX_TASK_ID='extract_text_from_pdf' AIRFLOW_CTX_EXECUTION_DATE='2023-10-17T10:15:23.376443+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-17T10:15:23.376443+00:00'
[2023-10-17T15:45:26.099+0530] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/harika/airflow/dags/pdf_extract.py", line 8, in extract_text_from_pdf
    pdf_file = open(pdf_file_path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './sample.pdf'
[2023-10-17T15:45:26.102+0530] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=pdf_extract, task_id=extract_text_from_pdf, execution_date=20231017T101523, start_date=20231017T101525, end_date=20231017T101526
[2023-10-17T15:45:26.118+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 318 for task extract_text_from_pdf ([Errno 2] No such file or directory: './sample.pdf'; 39612)
[2023-10-17T15:45:26.130+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-17T15:45:26.143+0530] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
