[2023-10-23T16:57:10.859+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_dag.send_notification_email manual__2023-10-23T11:21:58.110622+00:00 [queued]>
[2023-10-23T16:57:10.865+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_dag.send_notification_email manual__2023-10-23T11:21:58.110622+00:00 [queued]>
[2023-10-23T16:57:10.865+0530] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-10-23T16:57:10.874+0530] {taskinstance.py:1380} INFO - Executing <Task(EmailOperator): send_notification_email> on 2023-10-23 11:21:58.110622+00:00
[2023-10-23T16:57:10.878+0530] {standard_task_runner.py:57} INFO - Started process 35609 to run task
[2023-10-23T16:57:10.880+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'wikipedia_dag', 'send_notification_email', 'manual__2023-10-23T11:21:58.110622+00:00', '--job-id', '820', '--raw', '--subdir', 'DAGS_FOLDER/word_count.py', '--cfg-path', '/tmp/tmpcb0xmxr5']
[2023-10-23T16:57:10.881+0530] {standard_task_runner.py:85} INFO - Job 820: Subtask send_notification_email
[2023-10-23T16:57:10.902+0530] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_dag.send_notification_email manual__2023-10-23T11:21:58.110622+00:00 [running]> on host harika-Latitude-5511
[2023-10-23T16:57:10.942+0530] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='harikasree2225@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='wikipedia_dag' AIRFLOW_CTX_TASK_ID='send_notification_email' AIRFLOW_CTX_EXECUTION_DATE='2023-10-23T11:21:58.110622+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-23T11:21:58.110622+00:00'
[2023-10-23T16:57:10.949+0530] {logging_mixin.py:151} WARNING - /home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-10-23T16:57:10.950+0530] {configuration.py:1063} WARNING - section/key [smtp/smtp_user] not found in config
[2023-10-23T16:57:10.950+0530] {email.py:270} INFO - Email alerting: attempt 1
[2023-10-23T16:57:10.950+0530] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/operators/email.py", line 77, in execute
    send_email(
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2023-10-23T16:57:10.953+0530] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=wikipedia_dag, task_id=send_notification_email, execution_date=20231023T112158, start_date=20231023T112710, end_date=20231023T112710
[2023-10-23T16:57:10.959+0530] {configuration.py:1063} WARNING - section/key [smtp/smtp_user] not found in config
[2023-10-23T16:57:10.959+0530] {email.py:270} INFO - Email alerting: attempt 1
[2023-10-23T16:57:10.961+0530] {configuration.py:1063} WARNING - section/key [smtp/smtp_user] not found in config
[2023-10-23T16:57:10.961+0530] {email.py:270} INFO - Email alerting: attempt 1
[2023-10-23T16:57:10.961+0530] {taskinstance.py:2005} ERROR - Failed to send email to: ['harikasree2225@gmail.com']
Traceback (most recent call last):
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/operators/email.py", line 77, in execute
    send_email(
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2418, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2003, in handle_failure
    self.email_alert(error, task)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2023-10-23T16:57:10.967+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 820 for task send_notification_email ([Errno 111] Connection refused; 35609)
[2023-10-23T16:57:11.011+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-23T16:57:11.024+0530] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
